const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs/promises');
const path = require('node:path');
(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
  const errors = [];
  try {
    await fs.mkdir('.impeccable/review', { recursive: true });
    await fs.mkdir('test-results', { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:3000'); await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: '.impeccable/review/desktop.png', fullPage: true });
    await page.getByRole('button', { name: 'Experimentar com exemplo' }).click();
    await page.getByRole('button', { name: 'Ler arquivo' }).click();
    await page.getByRole('heading', { name: 'Confira antes de baixar' }).waitFor();
    await page.locator('#rows tr').first().waitFor();
    if (await page.locator('#rows tr').count() !== 3) throw new Error('Expected 3 rows');
    await page.locator('#map-cep').selectOption('');
    await page.getByRole('button', { name: 'Atualizar prévia' }).click();
    await page.getByText('3 sem CEP', { exact: false }).waitFor();
    await page.locator('#map-cep').selectOption('CEP');
    await page.getByRole('button', { name: 'Atualizar prévia' }).click();
    await page.getByText('1 sem CEP', { exact: false }).waitFor();
    const pending = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Baixar XLSX' }).click();
    const download = await pending;
    await download.saveAs('test-results/browser-export.xlsx');
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({ path: '.impeccable/review/desktop-result.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo(0, 0));
    if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Page has horizontal overflow');
    await page.screenshot({ path: '.impeccable/review/mobile-result.png', fullPage: true });
    await page.locator('#operator').fill('Operadora corrigida');
    if (await page.locator('#results').isVisible()) throw new Error('Stale result after changing operator');
    await page.getByRole('button', { name: 'Ler arquivo' }).click();
    await page.getByRole('heading', { name: 'Confira antes de baixar' }).waitFor();
    if (!(await page.locator('#file-summary').innerText()).includes('Operadora corrigida')) throw new Error('Operator correction not applied');
    await page.reload(); await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: '.impeccable/review/mobile.png', fullPage: true });
    await page.locator('#operator').fill('Teste erro');
    await page.locator('#file').setInputFiles({ name: 'quebrado.kml', mimeType: 'application/xml', buffer: Buffer.from('<kml>') });
    await page.getByRole('button', { name: 'Ler arquivo' }).click();
    await page.getByRole('alert').waitFor();
    const alert = await page.getByRole('alert').innerText();
    if (!alert.includes('inválido')) throw new Error(`Unexpected error: ${alert}`);
    if (errors.length) throw new Error(errors.join('\n'));
    console.log('UI OK: upload, demo, remapping, real worker export, invalid file, desktop/mobile, no JS errors.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
